import { Inter } from "next/font/google";
import "./globals.css";
import { AppBody } from "./AppBody";
import { ModalProvider } from "@/context/ModalContext";

import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ModalProvider>
            <AppBody>{children}</AppBody>
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
