import { Inter } from "next/font/google";
import "./globals.css";
import { AppBody } from "./AppBody";
import { ModalProvider } from "@/context/ModalContext";
import { LoadingProvider } from "@/context/LoadingContext"; // Import LoadingProvider

import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inovindo Academy",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/images/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ModalProvider>
            <LoadingProvider>
              <AppBody>{children}</AppBody>
            </LoadingProvider>
          </ModalProvider>
        </AuthProvider>
        <script
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          data-client-key="SB-Mid-client-EKpKloyAMpZCbeJe"
        ></script>
      </body>
    </html>
  );
}
